Contentful to strapi migration
mbwatson/renci-dot-org pull request #19
Opened 2022-10-31 14:36 UTC by suejinkim20

Summary of changes:
- two new graphql fetch hooks have been created: `fetchStrapiGraphQL` and `fetchPeopleByPIDs`
     - `fetchStrapiGraphQL`: fetches strapi data from the graphql endpoint (https://api.renci.org/graphql)
          - future note: add an error message if no 200 status message
     - `fetchPeopleByPIDs`: a function that takes the array of PIDs, queries those people, and returns an array of people objects that you can reference in a future payload object
- projects are now pulling from strapi and queried in graphQL (both list of projects and individual projects)
- operational teams are now pulling from strapi and queried in graphQL (both list of teams and individual teams)
- research groups are now pulling from strapi and queried in graphQL(both list of groups and individual groups)
- collaborations are now pulling from strapi and queried in graphQL (both list of collaborations and individual collaborations)

note about the queries: the majority of the data manipulation happens in the graphql files, listed as _______GraphQL.js (collaborations, groups, teams, projects). due to the many layers of strapi data, this file flattens the object in an attempt to remove the `data` and `attributes` layers

2022-10-31 17:18 UTC, mbwatson commented on components/spotlight.js
> -import LinesEllipsis from 'react-lines-ellipsis'
does this mean we can we lose this dependency now?

2022-10-31 17:36 UTC, mbwatson requested changes
this looks great! i made a few comments, and i have just one more. don't forget to use the `lint` script to point out any ESlint warnings and errors that needs cleaning up.

```
$ npm run lint

> renci-dot-org@0.1.0 lint
> next lint

info  - Loaded env from /home/matt/dev/renci/renci-dot-org/client/.env.local

./pages/people/[slug].js
29:11  Warning: Image elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

./pages/people/index.js
35:6  Warning: React Hook useEffect has a missing dependency: 'people.ood'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/projects/[id].js
43:16  Error: Missing "key" prop for element in iterator  react/jsx-key
43:16  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
43:16  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text

./components/sections.js
61:9  Error: Missing "key" prop for element in iterator  react/jsx-key

./components/spotlight.js
122:6  Warning: React Hook useEffect has a missing dependency: 'projects'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

2022-10-31 17:36 UTC, mbwatson commented on components/spotlight.js
> +    <Card sx={styles.project} key={project.project_id}>
:+1:

2022-10-31 17:36 UTC, mbwatson commented on components/spotlight.js
> -import LinesEllipsis from 'react-lines-ellipsis'
does this mean we can we lose this dependency now?

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/collaborationsGraphQL.js
> +//create an array of PIDs for the members of the project
can we tidy up the indentation and comments. remove anything superfluous... for example, what's the comment on line 106 telling us?

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/collaborationsGraphQL.js
> +      members: peopleData && peopleData.map((member) => ({
if `peopleData` exists, we'd  get an array. otherwise, we should still get an array. this way the front-end can expect an array every time.

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/fetchPeopleByPIDs.js
> +      people(filters: {pid: { in: ["${formatPIDs}"] }}) {
i've seen several mismatched indentations. it's useful, visually, when these are all aligned correctly.

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/fetchStrapiGraphQL.js
> +export const fetchStrapiGraphQL = async (query, preview = false) => {
did we determine yet if this `preview` parameter is a thing here or an artifact of Contentful?

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/groups.js
> +const axios = require("axios");
ignoring these since they're going away

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/groupsGraphQL.js
> +import { fetchStrapiGraphQL } from './'
i don't think the staff photos come through as clean here as they do for projects yet. as in, sending the generic avatar url in lieu of their photo url if it doesn't exist.

2022-10-31 17:36 UTC, mbwatson commented on lib/strapi/groupsGraphQL.js
> +  const memberPIDs = await groupData.researchGroups.data[0].attributes.members.data.map((member)=> ( member.attributes.pid))
check syntax here. missing space. `.map((member)[space]=>( ...`

2022-11-04 17:43 UTC, suejinkim20 commented on components/spotlight.js
> -import LinesEllipsis from 'react-lines-ellipsis'
yes, it does! i'll commit that deletion in this PR

2022-11-10 14:35 UTC, mbwatson commented
i see the preview is failing with a vague "client-side" error. when i run your branch locally, i also see console errors; see screenshot.

![image](https://user-images.githubusercontent.com/6019870/201119189-2e8d1ac9-6acf-4918-b00a-1454d366298a.png)

do you see the same on your end?

2022-11-18 14:12 UTC, mbwatson approved these changes
:+1: it looks like all the pieces are in place. good job converting us over from Contentful to Strapi -- this was a big one!

2022-11-18 19:47 UTC, merged