Projects list search
mbwatson/renci-dot-org pull request #72
Opened 2023-11-28 14:15 UTC by scrummish

Hey yall, this is the search bar component.
Let me know your thoughts!

2023-11-28 15:40 UTC, Woozl reviewed
Looks pretty good. There seems to be a slight bug if I reload the page and then search an item and press enter on it in the list, which then displays the whole unfiltered list:

https://github.com/mbwatson/renci-dot-org/assets/16181779/8bde9fd8-2749-45e7-9e86-0ef2451ab92b

I wonder though if the autocomplete is needed here. I think a simple text input that filters and sorts the list would probably suffice, especially if the matching text could be highlighted or bolded in the project cards.

2023-11-28 15:40 UTC, Woozl commented on pages/projects/index.js
> +        options={projectsFiltered}
I think the autocomplete has the search and filtering functionality built-in to display the list of matching items, so I don't think it makes sense to filter the options? I may be wrong though.

2023-11-28 22:18 UTC, mbwatson commented
good bug-find, @Woozl. i missed that.

i'm wondering, too, now about autocomplete here. it seems that the filtered card and filtered terms are the same list, so a simple filter/search would likely suffice.

2023-11-29 19:02 UTC, mbwatson requested changes
after some thought, @scrummish, let's drop the autocomplete (as it's redundant functionality in this instance), and let's just have a plain ol' text input filter situation. can you make this adjustment?

2023-12-01 17:47 UTC, mbwatson requested changes
looks good. i think it's cleaner, but i think there's more to clean out with autocomplete gone. i don't see a difference regardless of whether `StyledAutocompleteSearch` is used. additionally, that `options` prop is now obsolete.

lastly, there's a `fullWidth` is prop available on `FormControl`, so the `width: '100%'` stuff can go away if that's used.

these changes should simplify the component and clean out the leftover autocomplete artifacts.

2023-12-01 18:07 UTC, Woozl approved these changes
👍

2024-02-22 19:17 UTC, merged