Feature/branding
mbwatson/renci-dot-org pull request #78
Opened 2023-12-15 15:39 UTC by suejinkim20

2024-02-01 16:36 UTC, mbwatson reviewed
the link on /about to /about/branding throws this error: 
![image](https://github.com/mbwatson/renci-dot-org/assets/6019870/cfd0f949-cf31-44ac-ad7b-db694ce238ab)
...but refreshing or directly accessing the page works as expected. this may be related to a similar issues @Woozl discovered while working on one of the News views.

the page looks great, though. we do not need that grey text showing the path, but i believe the image should be a link to the image path, which would open the image in a new tab.

2024-02-01 16:49 UTC, suejinkim20 commented
@mbwatson that's right! thank you for pointing that out. i had forgotten to update the brand portion.

i'll take a look at the error as well!

2024-02-08 16:29 UTC, mbwatson requested changes
yeah, this is looking really clean and professional! upon closer inspection, i see room for some code cleanup and slight re-organization. please let me know if any of my line comments are unclear.

2024-02-08 16:29 UTC, mbwatson commented on components/block.js
what is this component?

2024-02-08 16:29 UTC, mbwatson commented on components/branding/ColorBlock.js
> +const hexToRgb = (hex) => {
this doesn't need to live inside this component that gets recreated multiple times. let's pull this function out into our utils dir.

2024-02-08 16:29 UTC, mbwatson commented on images/branding/clearspace-logo.png
it's not clear what length x is labeling in this image. can't be the width of that side strip because that's labeled x/2 on the other side. if it's the height, then those "x/2"s don't look accurate.

2024-02-08 16:29 UTC, mbwatson commented on components/branding/ColorSection.js
> +  const { classes, colors } = props
looks like `classes` is unused

2024-02-08 16:29 UTC, mbwatson commented on components/branding/LogoBlock.js
> +      <CardContent sx={ styles.topper } style={{ backgroundColor: bgColor }}>
we should stick with the `sx` prop for these MUI components and not mix `sx` and `style`

2024-02-08 16:29 UTC, mbwatson commented on components/branding/LogoSection.js
> +          return <Grid item xs={12} md={ 6 } lg={4} sx={ styles.logoBlock } key={ logo.image }>
:+1: this responsiveness is nice

2024-02-08 16:29 UTC, mbwatson commented on components/layout/footer.js
> +              <li><Link to="/about/branding">Branding</Link></li>
:+1:

2024-02-08 16:29 UTC, mbwatson commented on hooks/index.js
> +export * from './copy-to-clipboard'
let's stick `copy-to-clipboard` in our `util` dir. the `hooks` dir is more reserved for these `use*` functions that hook into React's rendering lifecycle

2024-02-08 16:29 UTC, mbwatson commented on components/branding/LogoBlock.js
> +// Link component when upgrading to Nextjs v13
:+1:

2024-02-08 16:29 UTC, mbwatson commented on components/branding/InfoBlock.js
> +import FileCopyIcon from '@mui/icons-material/FileCopy';
i don't love the file imagery since we're not copying a file. consider alternative icons like MUI's ContentCopy, CopyAll, or ContentPaste.

2024-02-08 16:29 UTC, mbwatson commented on components/branding/InfoBlock.js
> +  const theme = useTheme()
doesn't look like `theme` is used anywhere

2024-02-08 16:29 UTC, mbwatson commented on components/branding/ColorBlock.js
> +          <InfoBlock copyable title="RGB" body={ colorRgb } style={styles.info}/>
i'd like for the full RGB color code syntax `rgb(r, g, b)` to land in my clipboard--not just `r, g, b`.

2024-02-08 16:29 UTC, mbwatson commented on components/branding/ColorBlock.js
> +        <CardContent sx={styles.colorChip} style={{ backgroundColor: colorHex }}/>
inconsistent indentation here.

2024-02-08 16:29 UTC, mbwatson commented on components/branding/InfoBlock.js
> +      onClick={()=> copyToClipboard(props.body)}
we're not checking copyable here, so it looks like we can still copy the color name with a click, just without visual indication. 

honestly, i think we can make the name copyable, too, and just drop the `copyable` prop.

2024-03-07 16:22 UTC, suejinkim20 commented
@mbwatson, thank you for all the helpful feedback! all requested changes have been implemented except for the updated image depicting the clear-space guidelines. the plan is to merge this branch and update the logo when it is completed by the graphics team

2024-03-20 17:16 UTC, mbwatson commented on images/branding/clearspace-logo.png
we'll push this through and clean up the image later

2024-03-20 18:35 UTC, mbwatson approved these changes
this all looks great. thanks for taking care of those code cleanup requests. we discussed the clearspace image--we'll fix later. there's on last nit-pick: i'd love for the user to see a little visual cue that the copy happened. however, i think there will be other opportunities for copyable text, so perhaps we improve this component when that time comes.

2024-03-25 18:36 UTC, Woozl approved these changes
This is awesome, looks fantastic!

2024-03-25 18:55 UTC, suejinkim20 commented
> this all looks great. thanks for taking care of those code cleanup requests. we discussed the clearspace image--we'll fix later. i have one last nit-pick: i'd love for the user to see a little visual cue that the copy happened. however, i think there will be other opportunities for copyable text, so perhaps we improve this component when that time comes.

Issues created: 
- #94 
- #95

2024-03-25 18:55 UTC, merged