Feature/project card
mbwatson/renci-dot-org pull request #87
Opened 2024-02-23 20:01 UTC by suejinkim20

2024-05-14 13:46 UTC, mbwatson commented on components/link.js
> +      <a className={ className } ref={ ref } {...props}>{ children }</a>
do we want props distributed into NextLink and a? an incoming prop like `key`, for example, we would not want this behavior, so it feels like we want to be a bit careful here.

2024-05-15 13:00 UTC, mbwatson requested changes
looks pretty good! i've requested a few minor changes. we can discuss as needed

2024-05-15 13:00 UTC, mbwatson commented on components/projects/project-card.js
> +        flex
?

2024-05-15 13:00 UTC, mbwatson commented on components/projects/project-card.js
> +              <Link to={`/groups`} style={{textDecoration: 'none', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '0.5rem'}}>
i don't see this stuff getting rendered

2024-05-15 13:00 UTC, mbwatson commented on components/projects/project-card.js
> +              <Link to={`/groups`} style={{textDecoration: 'none', textTransform: 'uppercase', letterSpacing: '0.4px', marginBottom: '0.5rem'}}>
and i don't love this one-off text styling. why 0.4px spacing here and not other places?

2024-05-15 13:00 UTC, mbwatson commented on components/projects/project-card.js
> +              <Chip label="ACTIVE" size="small" sx={{
i think we'll want to have other active/inactive artifacts. it would be worth reusing this component when that time comes.

2024-05-17 18:57 UTC, Woozl approved these changes

2024-05-17 18:57 UTC, Woozl commented on components/markdown.js
> +    <li style={{fontSize: '85%'}} {...props}>{children}</li>
This seems overreaching, for instance it's making the /about/facilities page look like this:

![image](https://github.com/RENCI/renci-dot-org/assets/16181779/964f8319-e5b6-4607-897b-babe2b345f54)

2024-05-17 19:05 UTC, merged